---
- name: Restart elastichq
  ansible.builtin.service:
    name: Elastichq
    state: restarted
    enabled: true

- name: Reload elastichq
  ansible.builtin.systemd:
    name: Elastichq
    state: reloaded

- name: Start elastichq
  ansible.builtin.systemd:
    name: Elastichq
    state: started
